// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package main

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"de":    &dictionary{index: deIndex, data: deData},
		"en":    &dictionary{index: enIndex, data: enData},
		"pt_BR": &dictionary{index: pt_BRIndex, data: pt_BRData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"There are %v flowers in our garden. %[1]v again\n": 0,
	"You have %d problems\n":                            1,
}

var deIndex = []uint32{ // 3 elements
	0x00000000, 0x0000003a, 0x00000073,
} // Size: 36 bytes

const deData string = "" + // Size: 115 bytes
	"\x04\x00\x01\x0a5\x02Es gibt %[1]v Blumen in unserem Garten. %[1]v wiede" +
	"r\x04\x00\x01\x0a4\x14\x01\x81\x01\x00\x02\x14\x02Du hast ein Problem" +
	"\x00\x17\x02Du hast %[1]d Probleme"

var enIndex = []uint32{ // 3 elements
	0x00000000, 0x00000038, 0x00000073,
} // Size: 36 bytes

const enData string = "" + // Size: 115 bytes
	"\x04\x00\x01\x0a3\x02There are %[1]v flowers in our garden. %[1]v again" +
	"\x04\x00\x01\x0a6\x14\x01\x81\x01\x00\x02\x15\x02You have one problem" +
	"\x00\x18\x02You have %[1]d problems"

var pt_BRIndex = []uint32{ // 3 elements
	0x00000000, 0x0000003b, 0x0000007c,
} // Size: 36 bytes

const pt_BRData string = "" + // Size: 124 bytes
	"\x04\x00\x01\x0a6\x02Existem %[1]v flores em nosso jardim. %[1]v novamen" +
	"te\x04\x00\x01\x0a<\x14\x01\x81\x01\x00\x02\x19\x02Você tem %[1]d proble" +
	"ma\x00\x1a\x02Você tem %[1]d problemas"

	// Total table size 462 bytes (0KiB); checksum: 835E4697
